name: Docker-React CI
on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build -t mijenne/docker-react -f Dockerfile.dev .
        docker run -e CI=true mijenne/docker-react npm run test -- --coverage
